import type { OrchState } from "./types";

// Same encoding as the public prompt-site: utf8 → base64url, with =/+// stripped.
// Decoding uses the inverse so links generated by either site interop.
export function encodeState(state: OrchState): string {
  const json = JSON.stringify(state);
  if (typeof Buffer !== "undefined") {
    return Buffer.from(json, "utf-8")
      .toString("base64")
      .replace(/\+/g, "-")
      .replace(/\//g, "_")
      .replace(/=+$/, "");
  }
  // Browser path: mirror the unescape/encodeURIComponent trick.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const _btoa: (s: string) => string = (globalThis as any).btoa;
  return _btoa(unescape(encodeURIComponent(json)))
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
}

export function decodeState(s: string): OrchState | null {
  try {
    let t = s.replace(/-/g, "+").replace(/_/g, "/");
    while (t.length % 4) t += "=";
    let json: string;
    if (typeof Buffer !== "undefined") {
      json = Buffer.from(t, "base64").toString("utf-8");
    } else {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const _atob: (s: string) => string = (globalThis as any).atob;
      json = decodeURIComponent(escape(_atob(t)));
    }
    const parsed = JSON.parse(json);
    if (!parsed || !parsed.pattern || !Array.isArray(parsed.agents)) return null;
    return parsed as OrchState;
  } catch {
    return null;
  }
}
